-- =============================================================
-- Sys_Language 多语言支持 - 数据库升级脚本 (SQL Server)
-- 生成时间: 2026-08-04
-- 内容:
--   1. 创建 Sys_Language 多语言翻译表(ZHCN为翻译key，其余列为对应语言翻译)
--   2. "语言设置"菜单(挂在与Sys_Role菜单相同的父级下)
--   3. 种子数据: 框架自带中英文翻译 290 条(来自前端uitils/translator/en.js)
-- 使用说明:
--   - 脚本可重复执行(幂等)
--   - 执行后在系统菜单[语言设置]维护翻译，点击[生成语言包]生成wwwroot/lang/{en,zh-tw,fr,es,ru,ar}.js
--   - 前端登录页/顶部导航切换语言(需main.js中$global.lang=true)
-- =============================================================

-- 1. Sys_Language 表
IF OBJECT_ID('Sys_Language', 'U') IS NULL
BEGIN
    CREATE TABLE Sys_Language (
        Id INT PRIMARY KEY IDENTITY(1,1),
        ZHCN NVARCHAR(500) NOT NULL,
        ZHTW NVARCHAR(1000) NULL,
        English NVARCHAR(1000) NULL,
        French NVARCHAR(1000) NULL,
        Spanish NVARCHAR(1000) NULL,
        Russian NVARCHAR(1000) NULL,
        Arabic NVARCHAR(1000) NULL,
        Module NVARCHAR(100) NULL,
        IsPackageContent INT NULL DEFAULT 1,
        CreateID INT NULL,
        Creator NVARCHAR(255) NULL,
        CreateDate DATETIME NULL DEFAULT GETDATE(),
        ModifyID INT NULL,
        Modifier NVARCHAR(255) NULL,
        ModifyDate DATETIME NULL
    );
    PRINT 'Sys_Language created';
END
ELSE
    PRINT 'Sys_Language exists, skip';
GO

-- 2. "语言设置"菜单：挂到与"角色管理"(Sys_Role)相同的父级菜单下
IF NOT EXISTS (SELECT 1 FROM Sys_Menu WHERE TableName = 'Sys_Language')
BEGIN
    DECLARE @parentId INT = (SELECT TOP 1 ParentId FROM Sys_Menu WHERE TableName = 'Sys_Role');
    IF @parentId IS NULL SET @parentId = 0;
    INSERT INTO Sys_Menu (ParentId, MenuName, TableName, Url, Auth, Icon, OrderNo, Enable, MenuType, Creator, CreateDate)
    VALUES (@parentId, N'语言设置', 'Sys_Language', '/Sys_Language',
            '[{"text":"查询","value":"Search"},{"text":"新建","value":"Add"},{"text":"删除","value":"Delete"},{"text":"编辑","value":"Update"},{"text":"导出","value":"Export"}]',
            'el-icon-connection', 901, 1, 0, 'admin', GETDATE());
    PRINT 'menu Sys_Language created';
END
ELSE
    PRINT 'menu Sys_Language exists, skip';
GO

-- 3. 种子数据(仅空表时导入)
IF NOT EXISTS (SELECT 1 FROM Sys_Language)
BEGIN
INSERT INTO Sys_Language (ZHCN, English, IsPackageContent, Creator, CreateDate) VALUES
    (N'审批流程', N'workflow', 1, 'admin', GETDATE()),
    (N'基础设置', N'settings', 1, 'admin', GETDATE()),
    (N'基础组件', N'components', 1, 'admin', GETDATE()),
    (N'框架文档', N'Document', 1, 'admin', GETDATE()),
    (N'仓库管理', N'Warehouse', 1, 'admin', GETDATE()),
    (N'设备管理', N'Equipment', 1, 'admin', GETDATE()),
    (N'最多只能选[5]张图片', N'You can only select [5] pictures at most', 1, 'admin', GETDATE()),
    (N'最多只能选[5]个文件', N'Only [5] files can be selected at most', 1, 'admin', GETDATE()),
    (N'只能选择excel文件', N'Only Excel files can be selected', 1, 'admin', GETDATE()),
    (N'文件大小不能超过', N'The file size cannot exceed', 1, 'admin', GETDATE()),
    (N'最多可输入[{$ts}]个字符', N'a maximum of [{$ts}] characters can be entered', 1, 'admin', GETDATE()),
    (N'第[{$ts}]行,[{$ts}]验证未通过', N'Line [{$ts},{$ts}] failed verificatio', 1, 'admin', GETDATE()),
    (N'删除成功,共[{$ts}]条数据', N'Deletion succeeded, with a total of [{$ts}] data', 1, 'admin', GETDATE()),
    (N'[{$ts}]不能为空', N'[{$ts}] is required', 1, 'admin', GETDATE()),
    (N'[{$ts},{$ts}]不能为空', N'[{$ts},{$ts}] is required', 1, 'admin', GETDATE()),
    (N'无数据', N'No data', 1, 'admin', GETDATE()),
    (N'[{$ts}]重复', N'[{$ts}] repeated', 1, 'admin', GETDATE()),
    (N'搜索', N'Search', 1, 'admin', GETDATE()),
    (N'详情', N'Details', 1, 'admin', GETDATE()),
    (N'重复', N'repeated', 1, 'admin', GETDATE()),
    (N'重复记录', N'Repeated recording', 1, 'admin', GETDATE()),
    (N'重置', N'Reset', 1, 'admin', GETDATE()),
    (N'重置筛选条件', N'Reset filter', 1, 'admin', GETDATE()),
    (N'角色管理', N'Role info', 1, 'admin', GETDATE()),
    (N'角色名称', N'Role', 1, 'admin', GETDATE()),
    (N'角色', N'Role', 1, 'admin', GETDATE()),
    (N'设置', N'Setting', 1, 'admin', GETDATE()),
    (N'保存筛选条件', N'Save filter', 1, 'admin', GETDATE()),
    (N'保存成功,共{$ts}条数据', N'Saved successfully, {$ts} item in total', 1, 'admin', GETDATE()),
    (N'选择', N'Select', 1, 'admin', GETDATE()),
    (N'选择文件', N'Select file', 1, 'admin', GETDATE()),
    (N'请选择行', N'Please select rows', 1, 'admin', GETDATE()),
    (N'修改人', N'Modifier', 1, 'admin', GETDATE()),
    (N'修改密码', N'Password', 1, 'admin', GETDATE()),
    (N'修改时间', N'Modify time', 1, 'admin', GETDATE()),
    (N'模块', N'Module', 1, 'admin', GETDATE()),
    (N'月', N'Months', 1, 'admin', GETDATE()),
    (N'更多', N'More', 1, 'admin', GETDATE()),
    (N'名字', N'Name', 1, 'admin', GETDATE()),
    (N'邮箱', N'Mail', 1, 'admin', GETDATE()),
    (N'女', N'Male', 1, 'admin', GETDATE()),
    (N'男', N'Ma', 1, 'admin', GETDATE()),
    (N'菜单', N'Menu', 1, 'admin', GETDATE()),
    (N'菜单名称', N'Menu name', 1, 'admin', GETDATE()),
    (N'菜单设置', N'Menu', 1, 'admin', GETDATE()),
    (N'提示', N'Message', 1, 'admin', GETDATE()),
    (N'否', N'No', 1, 'admin', GETDATE()),
    (N'父级ID', N'Parent ID', 1, 'admin', GETDATE()),
    (N'上级角色', N'Parent role', 1, 'admin', GETDATE()),
    (N'密码', N'Password', 1, 'admin', GETDATE()),
    (N'权限', N'Permissio', 1, 'admin', GETDATE()),
    (N'个人中心', N'Personal Center', 1, 'admin', GETDATE()),
    (N'请输入', N'Please input', 1, 'admin', GETDATE()),
    (N'请选择', N'Please select', 1, 'admin', GETDATE()),
    (N'请选择文件', N'Please select file', 1, 'admin', GETDATE()),
    (N'其他', N'Other', 1, 'admin', GETDATE()),
    (N'必须是数字', N'not a number', 1, 'admin', GETDATE()),
    (N'备注', N'Notes', 1, 'admin', GETDATE()),
    (N'确认', N'OK', 1, 'admin', GETDATE()),
    (N'是', N'Yes', 1, 'admin', GETDATE()),
    (N'不存在', N'does not exist', 1, 'admin', GETDATE()),
    (N'系统', N'System', 1, 'admin', GETDATE()),
    (N'表名', N'Table Name', 1, 'admin', GETDATE()),
    (N'电话', N'Tel', 1, 'admin', GETDATE()),
    (N'时间', N'Time', 1, 'admin', GETDATE()),
    (N'排序号', N'Sort NO', 1, 'admin', GETDATE()),
    (N'状态', N'Status', 1, 'admin', GETDATE()),
    (N'操作成功', N'Success', 1, 'admin', GETDATE()),
    (N'删除成功', N'Successfully Delete', 1, 'admin', GETDATE()),
    (N'保存成功', N'Successfully save', 1, 'admin', GETDATE()),
    (N'摘要', N'Summary', 1, 'admin', GETDATE()),
    (N'超级管理员', N'Super Admi', 1, 'admin', GETDATE()),
    (N'确定', N'Confirm', 1, 'admin', GETDATE()),
    (N'用户管理', N'User info', 1, 'admin', GETDATE()),
    (N'用户名', N'Account', 1, 'admin', GETDATE()),
    (N'用户权限', N'User permission', 1, 'admin', GETDATE()),
    (N'用户基础信息', N'User info', 1, 'admin', GETDATE()),
    (N'用户名或密码错误', N'Account or password incorrect', 1, 'admin', GETDATE()),
    (N'值', N'Value', 1, 'admin', GETDATE()),
    (N'查看', N'View', 1, 'admin', GETDATE()),
    (N'警告', N'Warning', 1, 'admin', GETDATE()),
    (N'最多{$ts}个字符', N'Up to {$ts} characters', 1, 'admin', GETDATE()),
    (N'上传文件', N'Upload', 1, 'admin', GETDATE()),
    (N'上传', N'Upload', 1, 'admin', GETDATE()),
    (N'文件上传成功', N'Upload succeeded', 1, 'admin', GETDATE()),
    (N'代码生成', N'Coder', 1, 'admin', GETDATE()),
    (N'公司名称', N'Company', 1, 'admin', GETDATE()),
    (N'公司地址', N'Company address', 1, 'admin', GETDATE()),
    (N'公司管理', N'Company info', 1, 'admin', GETDATE()),
    (N'所属公司', N'Company name', 1, 'admin', GETDATE()),
    (N'公司类别', N'Company type', 1, 'admin', GETDATE()),
    (N'保存后继续添加', N'Continue adding after saving', 1, 'admin', GETDATE()),
    (N'成本', N'Cost', 1, 'admin', GETDATE()),
    (N'国家', N'Country', 1, 'admin', GETDATE()),
    (N'国家代码', N'CountryCode', 1, 'admin', GETDATE()),
    (N'创建时间', N'Create time', 1, 'admin', GETDATE()),
    (N'创建人', N'Creator', 1, 'admin', GETDATE()),
    (N'验证码', N'code', 1, 'admin', GETDATE()),
    (N'关闭', N'Close', 1, 'admin', GETDATE()),
    (N'只能是日期格式', N'Can only be in date format', 1, 'admin', GETDATE());
INSERT INTO Sys_Language (ZHCN, English, IsPackageContent, Creator, CreateDate) VALUES
    (N'取消', N'Cancel', 1, 'admin', GETDATE()),
    (N'不能大于', N'cannot be greater tha', 1, 'admin', GETDATE()),
    (N'不能小于', N'cannot be less tha', 1, 'admin', GETDATE()),
    (N'选中checkbox隐藏/显示列数据', N'Select check box to hide / show column data', 1, 'admin', GETDATE()),
    (N'中国', N'China', 1, 'admin', GETDATE()),
    (N'中文', N'Chinese', 1, 'admin', GETDATE()),
    (N'描述', N'Descriptio', 1, 'admin', GETDATE()),
    (N'数据字典', N'Dictionary', 1, 'admin', GETDATE()),
    (N'字典名称', N'Dictionary Name', 1, 'admin', GETDATE()),
    (N'字典编号', N'Dictionary Number', 1, 'admin', GETDATE()),
    (N'完成', N'Done', 1, 'admin', GETDATE()),
    (N'字典数据', N'Data Source', 1, 'admin', GETDATE()),
    (N'数据源', N'Data Source', 1, 'admin', GETDATE()),
    (N'下拉框绑定设置', N'Data source', 1, 'admin', GETDATE()),
    (N'日期', N'Date', 1, 'admin', GETDATE()),
    (N'删除', N'Delete', 1, 'admin', GETDATE()),
    (N'天', N'Days', 1, 'admin', GETDATE()),
    (N'帐号', N'Account', 1, 'admin', GETDATE()),
    (N'操作类型', N'Action type', 1, 'admin', GETDATE()),
    (N'新建', N'Add', 1, 'admin', GETDATE()),
    (N'添加子级', N'Add a subset', 1, 'admin', GETDATE()),
    (N'添加备注', N'Add note', 1, 'admin', GETDATE()),
    (N'添加行', N'Add Row', 1, 'admin', GETDATE()),
    (N'添加同级', N'Add Siblings', 1, 'admin', GETDATE()),
    (N'地址', N'Address', 1, 'admin', GETDATE()),
    (N'全选', N'All', 1, 'admin', GETDATE()),
    (N'不能为空', N'is required', 1, 'admin', GETDATE()),
    (N'参数设置', N'Parameters', 1, 'admin', GETDATE()),
    (N'真实姓名', N'Real Name', 1, 'admin', GETDATE()),
    (N'【{$ts}】不是模板中的列', N'【{$ts}】 is not a column in the template', 1, 'admin', GETDATE()),
    (N'第[{$ts}]行,[{$ts}]验证未通过,必须是日期格式', N'Line [{$ts},{$ts}] validation failed, must be in date format', 1, 'admin', GETDATE()),
    (N'第[{$ts}]行,[{$ts}]验证未通过,不能为空', N'Line [{$ts},{$ts}] failed verification, cannot be empty', 1, 'admin', GETDATE()),
    (N'[{$ts}]数据字典缺失', N'[{$ts}] no data source is configured', 1, 'admin', GETDATE()),
    (N'第[{$ts}]行,[{$ts}]验证未通过,只能输入', N'Line [{$ts},{$ts}] failed verification, only input', 1, 'admin', GETDATE()),
    (N'账号登录', N'Login account', 1, 'admin', GETDATE()),
    (N'正在登陆', N'Logging', 1, 'admin', GETDATE()),
    (N'登录', N'Login', 1, 'admin', GETDATE()),
    (N'登陆成功', N'Login Succeeded', 1, 'admin', GETDATE()),
    (N'语言设置', N'Language', 1, 'admin', GETDATE()),
    (N'系统设置', N'System', 1, 'admin', GETDATE()),
    (N'日志管理', N'Logger', 1, 'admin', GETDATE()),
    (N'英文', N'English', 1, 'admin', GETDATE()),
    (N'德语', N'Deutsch', 1, 'admin', GETDATE()),
    (N'印尼语', N'Indonesia', 1, 'admin', GETDATE()),
    (N'语言包', N'Package', 1, 'admin', GETDATE()),
    (N'权限管理', N'Permission', 1, 'admin', GETDATE()),
    (N'其他权限', N'Other', 1, 'admin', GETDATE()),
    (N'菜单列表', N'Menu list', 1, 'admin', GETDATE()),
    (N'确认要删除选择的数据吗?', N'Are you sure you want to delete the selected data?', 1, 'admin', GETDATE()),
    (N'正在处理', N'Processing', 1, 'admin', GETDATE()),
    (N'查询', N'Search', 1, 'admin', GETDATE()),
    (N'编辑', N'Edit', 1, 'admin', GETDATE()),
    (N'生成语言包', N'Create package', 1, 'admin', GETDATE()),
    (N'导入', N'Import', 1, 'admin', GETDATE()),
    (N'导出', N'Export', 1, 'admin', GETDATE()),
    (N'新增', N'Add', 1, 'admin', GETDATE()),
    (N'请输入正确的手机号', N'Please input the correct mobile phone number', 1, 'admin', GETDATE()),
    (N'密码长度不能小于6位', N'The password length cannot be less than 6 digits', 1, 'admin', GETDATE()),
    (N'只能是整数', N'required is an integer', 1, 'admin', GETDATE()),
    (N'只能是数字', N'required are numbers', 1, 'admin', GETDATE()),
    (N'必须是一个邮箱地址', N'It must be an email address', 1, 'admin', GETDATE()),
    (N'是否启用', N'Enable', 1, 'admin', GETDATE()),
    (N'sql语句', N'Sql', 1, 'admin', GETDATE()),
    (N'旧密码不能为空', N'Old password cannot be empty\r\n', 1, 'admin', GETDATE()),
    (N'新密码不能为空', N'New password cannot be empty', 1, 'admin', GETDATE()),
    (N'旧密码不正确', N'The old password is incorrect', 1, 'admin', GETDATE()),
    (N'新密码不能与旧密码相同', N'The new password cannot be the same as the old password', 1, 'admin', GETDATE()),
    (N'密码修改成功\r\n', N'Password modified successfully', 1, 'admin', GETDATE()),
    (N'不能选择此角色', N'This role cannot be selected', 1, 'admin', GETDATE()),
    (N'用户名已经被注册\r\n', N'The user name has been registered', 1, 'admin', GETDATE()),
    (N'用户新建成功.帐号[{$ts}],密码[{$ts}]', N'User created successfully. Account number [{$ts}], password [{$ts}]', 1, 'admin', GETDATE()),
    (N'没有权限', N'No permission', 1, 'admin', GETDATE()),
    (N'不能修改自己的角色', N'You cannot modify your own role', 1, 'admin', GETDATE()),
    (N'角色名【{$ts}】已存在', N'Role name [{$ts}] already exists\r\n', 1, 'admin', GETDATE()),
    (N'上级角色不能选择自己', N'Superior roles cannot choose themselves', 1, 'admin', GETDATE()),
    (N'不能选择此上级角色，选择的上级角色与当前角色形成依赖关系', N'This superior role cannot be selected. The selected superior role is dependent on the current role', 1, 'admin', GETDATE()),
    (N'服务器处理出现异常', N'Server processing exceptio', 1, 'admin', GETDATE()),
    (N'未找到上传的文件', N'Upload file not found', 1, 'admin', GETDATE()),
    (N'[{$ts}]不是模板中的列', N'[{$ts}] is not a column in the template', 1, 'admin', GETDATE()),
    (N'[{$ts}]列名重复', N'Duplicate column name [{$ts}]', 1, 'admin', GETDATE()),
    (N'导入文件列必须与导入模板相同', N'The import file columns must be the same as the import template', 1, 'admin', GETDATE()),
    (N'下载模板', N'Download template', 1, 'admin', GETDATE()),
    (N'上传结果', N'Import result', 1, 'admin', GETDATE()),
    (N'保存', N'Save', 1, 'admin', GETDATE()),
    (N'请上传文件', N'Please upload the file', 1, 'admin', GETDATE()),
    (N'上传失败', N'Upload failed', 1, 'admin', GETDATE()),
    (N'皮肤', N'Theme', 1, 'admin', GETDATE()),
    (N'安全退出', N'Log out', 1, 'admin', GETDATE()),
    (N'首页', N'Home', 1, 'admin', GETDATE()),
    (N'角色ID', N'Role ID', 1, 'admin', GETDATE()),
    (N'部门名称', N'Department', 1, 'admin', GETDATE()),
    (N'删除行', N'Delete row', 1, 'admin', GETDATE()),
    (N'刷新', N'Refresh', 1, 'admin', GETDATE()),
    (N'字典明细', N'Dictionary details', 1, 'admin', GETDATE()),
    (N'是否可用', N'Enable', 1, 'admin', GETDATE()),
    (N'数据源Text', N'Text', 1, 'admin', GETDATE()),
    (N'数据源Value', N'Value', 1, 'admin', GETDATE()),
    (N'数据源ID', N'ID', 1, 'admin', GETDATE()),
    (N'系统日志', N'Logger', 1, 'admin', GETDATE()),
    (N'开始时间', N'Start time', 1, 'admin', GETDATE());
INSERT INTO Sys_Language (ZHCN, English, IsPackageContent, Creator, CreateDate) VALUES
    (N'用户名称', N'Name', 1, 'admin', GETDATE()),
    (N'请求地址', N'Url', 1, 'admin', GETDATE()),
    (N'日志类型', N'Log type', 1, 'admin', GETDATE()),
    (N'响应状态', N'Status', 1, 'admin', GETDATE()),
    (N'时长', N'Duratio', 1, 'admin', GETDATE()),
    (N'请求参数', N'Request', 1, 'admin', GETDATE()),
    (N'响应参数', N'Response', 1, 'admin', GETDATE()),
    (N'异常信息', N'Exception', 1, 'admin', GETDATE()),
    (N'用户IP', N'User IP', 1, 'admin', GETDATE()),
    (N'浏览器类型', N'Browser', 1, 'admin', GETDATE()),
    (N'性别', N'Gender', 1, 'admin', GETDATE()),
    (N'操作', N'Actio', 1, 'admin', GETDATE()),
    (N'头像', N'Header', 1, 'admin', GETDATE()),
    (N'注册时间', N'Reg time', 1, 'admin', GETDATE()),
    (N'审核', N'Audit', 1, 'admin', GETDATE()),
    (N'视图/表名', N'Table/View', 1, 'admin', GETDATE()),
    (N'菜单ID', N'Menu ID', 1, 'admin', GETDATE()),
    (N'用户信息', N'User info', 1, 'admin', GETDATE()),
    (N'验证码不正确', N'Incorrect verification code', 1, 'admin', GETDATE()),
    (N'手机用户', N'Mobile users', 1, 'admin', GETDATE()),
    (N'语言管理', N'Language', 1, 'admin', GETDATE()),
    (N'简体中文', N'zh-cn', 1, 'admin', GETDATE()),
    (N'繁体中文', N'zh-tw', 1, 'admin', GETDATE()),
    (N'英语', N'English', 1, 'admin', GETDATE()),
    (N'法语', N'French', 1, 'admin', GETDATE()),
    (N'西班牙语', N'Spanish', 1, 'admin', GETDATE()),
    (N'俄语', N'Russian', 1, 'admin', GETDATE()),
    (N'高级查询', N'Query', 1, 'admin', GETDATE()),
    (N'角色列表', N'Role list', 1, 'admin', GETDATE()),
    (N'姓名', N'Name', 1, 'admin', GETDATE()),
    (N'阿拉伯语', N'Arabic', 1, 'admin', GETDATE()),
    (N'只能上传excel文件,文件大小不超过5M', N'Only Excel files can be uploaded, and the file size shall not exceed 5m', 1, 'admin', GETDATE()),
    (N'选择的文件【{$ts}】只能是excel文件', N'The selected file [{$ts}] can only be an excel file', 1, 'admin', GETDATE()),
    (N'选择的文件【{$ts}】只能是图片格式', N'The selected file [{$ts}] can only be in picture format', 1, 'admin', GETDATE()),
    (N'最多只能选【{$ts}】张图片', N'You can only select [{$ts}] pictures at most', 1, 'admin', GETDATE()),
    (N'最多只能选【{$ts}】个文件', N'You can only select [{$ts}] files at most', 1, 'admin', GETDATE()),
    (N'不支持此文件格式', N'This file format is not supported', 1, 'admin', GETDATE()),
    (N'文件不能超过[{$ts}]m', N'File cannot exceed [{$ts}] m', 1, 'admin', GETDATE()),
    (N'上传中', N'Uploading', 1, 'admin', GETDATE()),
    (N'文件列表', N'File list', 1, 'admin', GETDATE()),
    (N'文件名', N'Filen name', 1, 'admin', GETDATE()),
    (N'大小', N'Size', 1, 'admin', GETDATE()),
    (N'未能处理导入的文件,请检查导入的文件是否正确', N'Failed to process the imported file. Please check whether the imported file is correct', 1, 'admin', GETDATE()),
    (N'Token已过期', N'The token has expired', 1, 'admin', GETDATE()),
    (N'密码长度不能少于6位', N'Password length cannot be less than 6', 1, 'admin', GETDATE()),
    (N'密码修改成功', N'Password modified successfully', 1, 'admin', GETDATE()),
    (N'用户不存在', N'user does not exist', 1, 'admin', GETDATE()),
    (N'当前菜单存在子菜单,请先删除子菜单', N'There are sub menus in the current menu. Please delete the sub menu first', 1, 'admin', GETDATE()),
    (N'【字典项名称】不能有重复的值', N'[dictionary item name] cannot have duplicate values', 1, 'admin', GETDATE()),
    (N'【字典项Key】不能有重复的值', N'[dictionary key] cannot have duplicate values', 1, 'admin', GETDATE()),
    (N'字典编号[{$ts}]已存在', N'Dictionary number [{$ts}] already exists\n\n', 1, 'admin', GETDATE()),
    (N'账号', N'account', 1, 'admin', GETDATE()),
    (N'越南语', N'Vietnamese', 1, 'admin', GETDATE()),
    (N'泰语', N'Thai', 1, 'admin', GETDATE()),
    (N'结束时间', N'End time', 1, 'admin', GETDATE()),
    (N'是否显示', N'Show or not', 1, 'admin', GETDATE()),
    (N'列名', N'Field', 1, 'admin', GETDATE()),
    (N'拖动列名可调整表格列显示顺序', N'Drag column names to adjust the display order of table columns', 1, 'admin', GETDATE()),
    (N'集团租户', N'Group', 1, 'admin', GETDATE()),
    (N'组织构架', N'Organizational', 1, 'admin', GETDATE()),
    (N'集团管理', N'Group', 1, 'admin', GETDATE()),
    (N'数据分库', N'Database', 1, 'admin', GETDATE()),
    (N'演示菜单', N'Example', 1, 'admin', GETDATE()),
    (N'表单设计', N'Form Design', 1, 'admin', GETDATE()),
    (N'流程管理', N'Workflow', 1, 'admin', GETDATE()),
    (N'一对多生成', N'Multiple Tables', 1, 'admin', GETDATE()),
    (N'新窗口编辑', N'New Tab', 1, 'admin', GETDATE()),
    (N'打印设计', N'Print', 1, 'admin', GETDATE()),
    (N'消息推送', N'Message', 1, 'admin', GETDATE()),
    (N'定时任务', N'Tasks', 1, 'admin', GETDATE()),
    (N'名称', N'Name', 1, 'admin', GETDATE()),
    (N'编号', N'Code', 1, 'admin', GETDATE()),
    (N'类型', N'Type', 1, 'admin', GETDATE()),
    (N'集团名称', N'Group name', 1, 'admin', GETDATE()),
    (N'大屏数据', N'Data', 1, 'admin', GETDATE()),
    (N'MES业务', N'MES', 1, 'admin', GETDATE()),
    (N'工作台设计器', N'Workbench Designer', 1, 'admin', GETDATE()),
    (N'数据验证未通过!', N'Data validation failed!', 1, 'admin', GETDATE()),
    (N'开发文档', N'Document', 1, 'admin', GETDATE()),
    (N'外部链接', N'Link', 1, 'admin', GETDATE()),
    (N'窗口编辑', N'Window Edit', 1, 'admin', GETDATE()),
    (N'报表管理', N'Report', 1, 'admin', GETDATE()),
    (N'单据编码', N'Document code', 1, 'admin', GETDATE()),
    (N'工作台', N'Workstation', 1, 'admin', GETDATE()),
    (N'租户分库', N'Tenant Management', 1, 'admin', GETDATE()),
    (N'组件示例', N'Component Example', 1, 'admin', GETDATE()),
    (N'组件扩展', N'Component extension', 1, 'admin', GETDATE()),
    (N'已签收', N'已签收-01', 1, 'admin', GETDATE()),
    (N'业务系统', N'Business system', 1, 'admin', GETDATE()),
    (N'系统管理', N'System management', 1, 'admin', GETDATE());
    PRINT 'Sys_Language seeded';
END
ELSE
    PRINT 'Sys_Language has data, skip seed';
GO
